### ISSUE TITLE
Undesired behavior via `pauseInstanceWhileRefreshing` flag

### ISSUE THREAD

**Issue by huttj-lowes** [Flyrell/axios-auth-refresh#113]
I am using this library to refresh an OAuth2 token, and it works really well.

Unfortunately, it seems like I'm unable to get it to work exactly as I want. I want it to.

What I want is for it to pause all requests until the refresh flow completes, _and_ retry the other failed requests that were sent _before_ the flow was started.

The library seems to let me do one or the other, but not both.

Here's what it looks like when I set `pauseInstanceWhileRefreshing` to `true`:

![image](https://user-images.githubusercontent.com/65150715/92700263-7add5b00-f303-11ea-978a-08015b98ee29.png)

All of the failed requests are sent before the refresh flow is started (the `reset?req=...` as well as the `timeout-500` one). The first one (`resets?req=3`) is retried _after_ the flow completes, but the others are just dropped.

The other timeout ones are ostensibly sent wile the flow is in-progress, and those are paused until the flow completed (desired behavior).

I'd like a way to retry the pre-flow ones that failed.

Here's what I get if I turn the flag off:

![image](https://user-images.githubusercontent.com/65150715/92700758-0e169080-f304-11ea-8562-1b6c756a07a7.png)

All of the failed requests are retried, which is exactly what I want, but also requests that are sent _after_ the flow is started are not paused, resulting in more failed requests than necessary.

Still, the failures are hidden from the callers, which is what I want in either case, so that's good.

**Comment by Flyrell** [comment]
Would you please share you code & how you use the library?

**Comment by Flyrell** [comment]
Will reopen if anyone sends more information.

**Comment by huttj-lowes** [comment]
Apologies for the delay. Here's a code sample:

```javascript
createAuthRefreshInterceptor(axios, async (failedRequest) => {
  const token = Token.load();
  if (token) {
    const { data } = await axios.post(TOKEN_URL, token, {
      // eslint-disable-next-line
      // @ts-ignore
      skipAuthRefresh: true,
    });

    Token.save(data);

    failedRequest.response.config.headers.Authorization = `Bearer ${token.id_token}`;
  } else {
    throw new Error("Not logged in");
  }
});

axios.interceptors.request.use((request) => {
  const token = Token.load();
  if (token) {
    request.headers.Authorization = `Bearer ${token.id_token}`;
  }
  return request;
});
```

This is the configuration that works as I want it, except that it lets extra failed requests through.

If I add `pauseInstanceWhileRefreshing: true` to the config:

```
createAuthRefreshInterceptor(axios, async (failedRequest) => {
  const token = Token.load();
  if (token) {
    const { data } = await axios.post(TOKEN_URL, token, {
      // eslint-disable-next-line
      // @ts-ignore
      skipAuthRefresh: true,
    });

    Token.save(data);

    failedRequest.response.config.headers.Authorization = `Bearer ${token.id_token}`;
  } else {
    throw new Error("Not logged in");
  }
}, {
  pauseInstanceWhileRefreshing: true
});
```

This causes some requests to be dropped, and not retried (the if several are sent simultaneously, they all fail, but only one is retried).

**Comment by fkapsahili** [comment]
Were you able to solve this issue?

**Comment by s-titov** [comment]
I have had the same problem, any solutions? 🤔
