### ISSUE TITLE
Still have problems with multiple request

### ISSUE THREAD

**Issue by Bartyee** [Flyrell/axios-auth-refresh#117]
Hi
I have problem with my multiple requests. Only the first 401 error probably getting new access token, second not. 
![2020-09-21 18_03_42-Window](https://user-images.githubusercontent.com/39925899/93792542-f3161b80-fc35-11ea-9e7a-474fddba4e0c.png)

Here is my code.
`import axios from "axios";
import createAuthRefreshInterceptor from "axios-auth-refresh";

const baseUrl = "https://****.com/";
const instance = axios.create({
  baseURL: baseUrl,
});

// Function that will be called to refresh authorization
const refreshAuthLogic = (failedRequest: any) =>
  axios
    .post("https://****/api/token/refresh/", {
      refresh: localStorage.getItem("refreshToken"),
    })
    .then((tokenRefreshResponse) => {
      localStorage.removeItem("accessToken");
      localStorage.setItem("accessToken", tokenRefreshResponse.data.access);

      console.log(tokenRefreshResponse.data.access);

      failedRequest.response.config.headers["Authorization"] =
        "Bearer " + tokenRefreshResponse.data.access;

      return Promise.resolve();
    });

createAuthRefreshInterceptor(instance, refreshAuthLogic);

export default instance;`
No matter if I set the newest options like skipWhileRefreshing, pauseInstanceWhileRefreshing - situation is the same. I tried previous closed issues but didnt work :(

**Comment by lensanag** [comment]
You need put the logic for set auth token on an axios interceptor as the example on documentation:
```
axios.interceptors.request.use(request => {
    request.headers['Authorization'] = `Bearer ${getAccessToken()}`;
    return request;
});
```
previusly you define the function getAccessToken for example on localStorage.

**Comment by Flyrell** [comment]
@lensanag is correct. You need to use an interceptor to bind the new token for the requests. Otherwise there's no way to bind it into the awaiting requests, unfortunately.

**Comment by Bartyee** [comment]
Ehh... I don't understand a little how I can add this all. 
So my code above is correct but I need to define additional lines of code like this @lensanag?
In getAccessToken I have to put only localstorage.getItem or I should put there axios get request for token?

**Comment by Flyrell** [comment]
Example from documentation:

```javascript
// Logic from above is here

// Obtain the fresh token each time the function is called
function getAccessToken() {
    return localStorage.getItem('token');
}

// Use interceptor to inject the token to requests
axios.interceptors.request.use(request => {
    request.headers['Authorization'] = `Bearer ${getAccessToken()}`;
    return request;
});
```

**Comment by Bartyee** [comment]
Still the same situation (same like on my added picture)
```js
import axios from "axios";
import createAuthRefreshInterceptor from "axios-auth-refresh";

const baseUrl = "https://***/";

const instance = axios.create({
  baseURL: baseUrl,
});

// Function that will be called to refresh authorization
const refreshAuthLogic = (failedRequest: any) =>
  axios
    .post("https://***/api/token/refresh/", {
      refresh: localStorage.getItem("refreshToken"),
    })
    .then((tokenRefreshResponse) => {
      localStorage.setItem("accessToken", tokenRefreshResponse.data.access);

      console.log(tokenRefreshResponse.data.access);

      failedRequest.response.config.headers["Authorization"] =
        "Bearer " + tokenRefreshResponse.data.access;
      return Promise.resolve();
    });

function getAccessToken() {
  return localStorage.getItem("accessToken");
}

// Use interceptor to inject the token to requests
axios.interceptors.request.use((request) => {
  request.headers["Authorization"] = `Bearer ${getAccessToken()}`;
  return request;
});

createAuthRefreshInterceptor(instance, refreshAuthLogic);

export default instance;
```

**Comment by Flyrell** [comment]
Well, it's probably because you mix `instance` and `axios` like it's the same thing. Try to use `instance` after it's created and it will work just fine 🙂 

So the final code would be:

```javascript
import axios from "axios";
import createAuthRefreshInterceptor from "axios-auth-refresh";

const baseUrl = "https://***/";

const instance = axios.create({
  baseURL: baseUrl,
});

// Function that will be called to refresh authorization
const refreshAuthLogic = (failedRequest: any) =>
  instance
    .post("https://***/api/token/refresh/", {
      refresh: localStorage.getItem("refreshToken"),
    })
    .then((tokenRefreshResponse) => {
      localStorage.setItem("accessToken", tokenRefreshResponse.data.access);

      console.log(tokenRefreshResponse.data.access);

      failedRequest.response.config.headers["Authorization"] =
        "Bearer " + tokenRefreshResponse.data.access;
      return Promise.resolve();
    });

function getAccessToken() {
  return localStorage.getItem("accessToken");
}

// Use interceptor to inject the token to requests
instance.interceptors.request.use((request) => {
  request.headers["Authorization"] = `Bearer ${getAccessToken()}`;
  return request;
});

createAuthRefreshInterceptor(instance, refreshAuthLogic);

export default instance;
```

**Comment by Bartyee** [comment]
> Well, it's probably because you mix `instance` and `axios` like it's the same thing. Try to use `instance` after it's created and it will work just fine 🙂
> 
> So the final code would be:
> 
> ```js
> import axios from "axios";
> import createAuthRefreshInterceptor from "axios-auth-refresh";
> 
> const baseUrl = "https://***/";
> 
> const instance = axios.create({
>   baseURL: baseUrl,
> });
> 
> // Function that will be called to refresh authorization
> const refreshAuthLogic = (failedRequest: any) =>
>   instance
>     .post("https://***/api/token/refresh/", {
>       refresh: localStorage.getItem("refreshToken"),
>     })
>     .then((tokenRefreshResponse) => {
>       localStorage.setItem("accessToken", tokenRefreshResponse.data.access);
> 
>       console.log(tokenRefreshResponse.data.access);
> 
>       failedRequest.response.config.headers["Authorization"] =
>         "Bearer " + tokenRefreshResponse.data.access;
>       return Promise.resolve();
>     });
> 
> function getAccessToken() {
>   return localStorage.getItem("accessToken");
> }
> 
> // Use interceptor to inject the token to requests
> instance.interceptors.request.use((request) => {
>   request.headers["Authorization"] = `Bearer ${getAccessToken()}`;
>   return request;
> });
> 
> createAuthRefreshInterceptor(instance, refreshAuthLogic);
> 
> export default instance;
> ```

.... 
I forgot about using instance instead axios ... xD Sorry, my fault because in other files Im importing this instance with "axios" export for "instance" ... Thanks!!!!!!!!!!!!!!!!!!!!!!
