### ISSUE TITLE
No explicit license in the repo

### ISSUE THREAD

**Issue by opritche** [Flyrell/axios-auth-refresh#124]
According to https://www.npmjs.com/package/axios-auth-refresh, the license is the MIT License, but this should be reflected in the repo. There will be people, or companies who want to use this but will not be able to without the explicit license in the repo.

Thanks!

**Comment by Flyrell** [comment]
I'm not very good with all the legal stuff behind open source project, so I'm sorry about it. Will do a proper research and add the explicit license with the new v3.1.0 update. Thanks.

**Comment by metapone** [comment]
Are you still working on this? GitHub has a dedicated [page](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to help you with this. They even created a website to explain in simple terms what each common license means here: https://choosealicense.com/

**Comment by HighGreat** [comment]
Thanks for this lib!
It would be nice if you could grant the explicit license to this library.
If you want to grant the MIT license, simply add a `LICENSE` file as described on the following page.
https://choosealicense.com/licenses/mit/
