### ISSUE TITLE
how to work with httpOnly cookies?

### ISSUE THREAD

**Issue by MeRahulAhire** [Flyrell/axios-auth-refresh#125]
Do you have any suggestion on how can I use this library with httpOnly cookie. Local storage isn't safe.

**Comment by Flyrell** [comment]
I actually use it with httpOnly cookies. In the case of httpOnly cookies, your server is setting everything up, so it should be enough to just call the refreshing endpoint in the callback function (so-called `refreshAuthLogic` here: https://github.com/Flyrell/axios-auth-refresh#syntax). This way your server will set the cookies and they should be bound onto all requests waiting in queue to be triggered once the refreshing call is successful.
