### ISSUE TITLE
Is there a way for subsequent requests to not be re tried if refresh token call fails?

### ISSUE THREAD

**Issue by fab7jj** [Flyrell/axios-auth-refresh#128]
Hello I implemented your library and had a question. First of all thanks a lot for providing such tool to the community, it is really helpful, much appreciated.  

Secondly, I have this case scenario not sure if something can be done about it.

![RefreshToken1](https://user-images.githubusercontent.com/40164436/98108021-a01dbe00-1e9b-11eb-91d5-64b02b1f0e51.PNG)

If you see the attached image above which shows the console, I was testing and basically My UI have a sidebar and quickly clicked on two menu items which initiate some requests.

As you can see after the verify/token request has failed (it returned 400) the other two calls still have been retried. Is there a way to avoid this?

Here below is my implementation:

```
const refreshAuthLogic = (failedRequest) => {

        const refreshToken = retrieveRefreshToken();

        const refreshTokenRequestBody = {
            grant_type: 'refresh_token',
            refresh_token: refreshToken
        };
        const refreshTokenRequestBodyStringified = qs.stringify(refreshTokenRequestBody);

        const refreshTokenRequestConfig = {
            skipAuthRefresh: true,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded'
            }
        }

        return appAPI.post('verify/token', refreshTokenRequestBodyStringified, refreshTokenRequestConfig).then(function (response) {

            failedRequest.response.config.headers['Authorization'] = `Bearer ${response.data.access_token}`;
            storeAuthTokens(response.data.access_token, response.data.refresh_token);

            return Promise.resolve();
        })
        .catch(function (error) {

            clearAuthTokens();

            appAuthDispatch({
                type: appAuthContextReducerActionTypesEnum.logOut
            });
        });
    };

    const options = {
        skipWhileRefreshing: false
    };

    createAuthRefreshInterceptor(appAPI, refreshAuthLogic, options);
```

**Comment by vchar00** [comment]
same problem

**Comment by vatsal-s** [comment]
I am also facing the same problem

**Comment by elixir14** [comment]
@fab7jj @vchar00 did you guys find any working solution?

**Comment by www-chique** [comment]
@fab7jj , @vchar00 , @vatsal-s 
You can use Promise.reject to cancel the request if refresh token logic fails.
Here is how I do it:
On the first line of the refresh logic, I save the oldToken in a variable.
After the refresh call is made, I match the oldToken with newToken.
If the newToken is not present or if newToken is same as oldToken, I use
`return Promise.reject()` instead of Promise.resolve()
That cancels the subsequent calls.

**Comment by Flyrell** [comment]
Just add `Promise.reject()` to your catch logic.

```javascript
.catch(function (error) {
    clearAuthTokens();
    appAuthDispatch({
        type: appAuthContextReducerActionTypesEnum.logOut
    });
    return Promise.reject();
});
```
