### ISSUE TITLE
Error when two requests with an invalid access token are placed directly after each other

### ISSUE THREAD

**Issue by no0by5** [Flyrell/axios-auth-refresh#13]
If my access token has expired and I submit two requests in a row, the interceptor that queues the other requests will not be applied fast enough. The auth refresh interceptor is trying to get a new refresh token twice, which of course fails because the second time the refresh token insn't valid anymore.

**Comment by Flyrell** [comment]
Thanks for submitting the issue @no0by5 and sorry for responding after quite some time. Plugin in-fact does that. I will try to work on that this weekend. In case you have already implemented it in your code I'd appreciate the PR. Thank you.

**Comment by no0by5** [comment]
Have you made any progress? Unfortunately, I did not really have time to face the problem, and my Javascript skills are also rather basic, so I have some problems finding a good solution. Thank you

**Comment by Flyrell** [comment]
Unfortunately, I have been working on something else right now and had no time to take a look on this. It should not be difficult, but I probably won't find much time this week, maybe next weekend/week would be possible.

**Comment by suweya** [comment]
This may solve this problem

**Comment by Flyrell** [comment]
Should be fixed in #25 alongside typescript support and unit tests. Will test and give you a feedback. In case you want to speed things up, I'd be more than happy if you can also test it. 
Thank you for you contribution!

**Comment by Flyrell** [comment]
Fixed in #27. Please, give it a try before I publish it as latest release (it's in beta now). 

```
npm install axios-auth-refresh@beta --save
```
