### ISSUE TITLE
Unable to install with axios 0.21.1 dependency

### ISSUE THREAD

**Issue by jagadeeshkoka** [Flyrell/axios-auth-refresh#135]
jaggu@JagguPro myahb-ui % npm i axios-auth-refresh
                      npm ERR! code ERESOLVE
                      npm ERR! ERESOLVE unable to resolve dependency tree
                      npm ERR! 
                      npm ERR! While resolving: myahb-ui@0.1.0
                      npm ERR! Found: axios@0.21.1
                      npm ERR! node_modules/axios
                      npm ERR!   axios@"^0.21.0" from the root project
                      npm ERR! 
                      npm ERR! Could not resolve dependency:
                      npm ERR! peer axios@"~0.18.0 || ~0.19.1 || ~0.20.0" from axios-auth-refresh@3.0.0
                      npm ERR! node_modules/axios-auth-refresh
                      npm ERR!   axios-auth-refresh@"*" from the root project
                      npm ERR! 
                      npm ERR! Fix the upstream dependency conflict, or retry
                      npm ERR! this command with --force, or --legacy-peer-deps
                      npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
                      npm ERR! 
                      
                      
                      Please help, should I downgrade my axios version ?

**Comment by Flyrell** [comment]
Will bump the version to support axios v0.21.0 in upcoming v3.1.0.
