### ISSUE TITLE
Add refresh fails logic

### ISSUE THREAD

**Issue by alexanderkraemer** [Flyrell/axios-auth-refresh#138]
Would it be feasible to add logic that enables the FE to react to a refresh-token failure, to get a new refresh-token/access-token?

Example:

1. clicking through some app
2. API returns 401 as the token expired
3. refresh process triggered
4. refresh API returns 401 as the token expired
5. FE shows Password popup, for the user to reauthenticate
6. FE reauthenticates using default auth API
7. API call from "2" retries and succeeds.

Example for password form screenshotted from stripe:
![Screenshot 2021-01-13 at 07 27 56](https://user-images.githubusercontent.com/6594774/104414649-ea44af00-5570-11eb-85be-ddbc4fb32604.png)

It might just be a method call right after the refresh fails, that either returns `null` or a token set.

Looking forward to your response!

**Comment by Flyrell** [comment]
Sure, makes sense to me. Will take a look at how difficult the implementation would be. Thanks for the idea.

**Comment by alexanderkraemer** [comment]
Let me know if I can help!

**Comment by Flyrell** [comment]
Well, I think it's possible now:

```
import axios from 'axios';
import createAuthRefreshInterceptor from 'axios-auth-refresh';

const refreshAuthLogic = failedRequest => axios.post('https://www.example.com/auth/token/refresh', {}, { 
skipAuthRefresh: true }).then(tokenRefreshResponse => {
    localStorage.setItem('token', tokenRefreshResponse.data.token);
    failedRequest.response.config.headers['Authorization'] = 'Bearer ' + tokenRefreshResponse.data.token;
    return Promise.resolve();
}).catch(e => {
    // show modal
    // do request -> if successful return Promise.resolve()
    // in case of any error return Promise.reject()
});

const authInterceptorId = createAuthRefreshInterceptor(axios, refreshAuthLogic);
```

**Comment by alexanderkraemer** [comment]
Looks great, I'll have a look and come back to you if anything is unclear!
Thanks anyway! :)
