### ISSUE TITLE
Retry all failed requests as soon as refresh is completed

### ISSUE THREAD

**Issue by alexanderkraemer** [Flyrell/axios-auth-refresh#139]
My app is doing several requests at once.
if e.g. the first request fails with a 401, the app still does the rest of the requests which also then return 401.
It would be nice, if axios is catching those requests, wait for the token refresh is done, and then execute those with the according new access token.
It will require a pre-request interceptor, that only triggers when tokenrefresh is running.

What do you think about that?

**Comment by Flyrell** [comment]
It's possible, but then the library would need to "synchronise" (or queue) all of the requests, as you don't know which one would fail (you'd need to sent them one-by-one, as right now they're sent simultaneously, e.g. before any of them gets the 401 response). I guess the best chance of dealing with it is to actually do it by yourself if that's your use case.

It might be worth, though, to create a library you're talking about and use the `axios-auth-refresh` as a refreshing step in that library.

**Comment by esbenvb** [comment]
@Flyrell 

I think I have a similar problem. When I open the app, it makes 3-4 calls to the backend, they all fail but also triggers a refresh of the access token, which is then used on the subsequent calls from the app. 

But a few things makes me wonder, maybe I need to understand it better:

1. I thought the initial call to `/api/currrentuser` that caused 401 should automatically be repeated after refreshing the token? 
2. I thought that `pauseInstanceWhileRefreshing: true` meant that all subsequent calls should be paused until the token was refreshed. Here it looks like they are not paused
3.  What do you mean by "sent one by one" vs simultaneously? In my case I do various calls from various places in the app, but I don't do anything to "bundle" these? Shouldn't the intercepter stop the call to `api/currentuser/notifications?offset=0&limit=100` and `api/news/...` until it knows if the first call gave a 401?

![image](https://user-images.githubusercontent.com/426051/133564403-621f03c0-cb16-4859-943a-1e751ed60c61.png)
