### ISSUE TITLE
Server-Side Request Forgery on axios

### ISSUE THREAD

**Issue by rokde** [Flyrell/axios-auth-refresh#141]
See https://www.npmjs.com/advisories/1594

**Overview**
The axios NPM package before 0.21.1 contains a Server-Side Request Forgery (SSRF) vulnerability where an attacker is able to bypass a proxy by providing a URL that responds with a redirect to a restricted host or IP address.

**Remediation**
Upgrade axios to 0.21.1 or later.

Could you please update your dependency and make a new release?

**Comment by Flyrell** [comment]
Will be released in no time in v3.1.0. Closing this issue as PR #140 is already merged and is waiting to be published. Thank you.
