### ISSUE TITLE
Unable to call multiple api inside interceptor

### ISSUE THREAD

**Issue by ekacahya21** [Flyrell/axios-auth-refresh#142]
Hi, first of all i'm really thankful to you for making great library, it's really helpful. I'm facing problem when making multiple call inside refreshToken interceptor.

Here i'm calling api bonuses which had 401, then 1st api triggered and succeed
<img width="1024" alt="Screen Shot 2021-01-26 at 21 50 02" src="https://user-images.githubusercontent.com/15162377/105861251-19532a00-6021-11eb-8b7d-50cb88239d09.png">

Then 2nd api triggered but never getting any response.
<img width="1028" alt="Screen Shot 2021-01-26 at 21 49 52" src="https://user-images.githubusercontent.com/15162377/105861567-6fc06880-6021-11eb-8287-58c89fae4bb2.png">

Here's my code.
<img width="787" alt="Screen Shot 2021-01-26 at 22 03 52" src="https://user-images.githubusercontent.com/15162377/105862544-78fe0500-6022-11eb-8a35-374ba29e1f7a.png">

Is this a bug, or there any way to solve my problem?

**Comment by Flyrell** [comment]
Right now, you're always returning a resolved promise due to the nature of the async/await function. If you want to reject the refresh, your refresh auth logic function should return `Promise.reject()` at some point, which will not trigger any queued requests.
