### ISSUE TITLE
Call oauth refreshAuthToken before first request

### ISSUE THREAD

**Issue by thomaschaaf** [Flyrell/axios-auth-refresh#147]
It would be great if the refreshAuthToken function would be called if no authorization header has been set. Currently the first request always causes a 401 and then I send an authenticated request. Currently this results in duplicate code:

```
export class CoiClient {
  private axios: AxiosInstance;

  constructor(url: string, private readonly oauth: Oauth) {
    const refreshAuthToken = async (failedRequest) => {
      const token = await this.oauth.getToken(null, null, [
        'get-contracts',
      ]);

      failedRequest.response.config.headers.Authorization = token;
    };

    this.axios = axios.create({
      baseURL: url,
    });

    createAuthRefreshInterceptor(this.axios, refreshAuthToken);
  }

  async getContracts() {
    const token = await this.oauth.getToken(null, null, [
      'get-contracts',
    ]);

    const contracts = await this.axios.get(
      `/api-v1/contracts`,
      { headers: { Authorization: token } }
    );

    return contracts;
  }
}
```

**Comment by Flyrell** [comment]
I'm not sure how this works, to be honest. You call the API without having `Authorization` header set if your token has expired? If so, you can always write your own custom request interceptor to run the refreshing logic for you. I'm not 100% sure if that should be in the scope of this library. Will close for now.
