### ISSUE TITLE
The request does not return to its original promise and instance is not paused until refresh is complete

### ISSUE THREAD

**Issue by ammarrush** [Flyrell/axios-auth-refresh#149]
I was using this library with its previous versions (worked great by the way 👍 ) but I decided to update axios's and its version because I was facing other problems. But now there is the problem that failed request due to 401 or 403 does not return to its original promise it just fires again and resolves.

Here is my logic for calling apis:
```
const refreshAuthLogic = (failedRequest) =>
  axios
    .post(`${process.env.API_BASE_URL}user/refresh/`, getFormData())
    .then((tokenRefreshResponse) => {
      console.log(tokenRefreshResponse.data.refresh_token)
      Cookies.set('token', tokenRefreshResponse.data.access_token, {
        expires: 1 / 24
      })
      Cookies.set('refreshToken', tokenRefreshResponse.data.refresh_token, {
        expires: 365
      })
      failedRequest.response.config.headers.Authorization = `Bearer ${
        tokenRefreshResponse.data.access_token
      }`
      return Promise.resolve()
    })
    .catch((error) => {
      // if(Cookies.get('refreshToken') == undefined && Cookies.get('token')) {
      Auth.signout()
      window.location.reload(false)
      // }
    })

const instance = axios.create({
  baseURL: process.env.API_BASE_URL
})
instance.interceptors.request.use((request) => {
  request.headers.Authorization = `Bearer ${Cookies.get('token')}`
  return request
})
createAuthRefreshInterceptor(instance, refreshAuthLogic, {
  statusCodes: [401, 403],
  pauseInstanceWhileRefreshing: true
})
export default instance
```

and I use the instance like:
```
const settingsPromise = API.get('user/settings/', {
      headers: { Authorization: `Bearer ${Cookies.get('token')}` }
    })

    const userDataPromise = API.get('user/profile/', {
      headers: { Authorization: `Bearer ${Cookies.get('token')}` }
    })

    Promise.all([settingsPromise, userDataPromise]).then((result) => {
      // other code
    })
```
and sometimes: 
```
API.get('user/settings/', {
      headers: { Authorization: `Bearer ${Cookies.get('token')}` }
    }).then((result) => {
      // other code
    })
```
but for these calls it does not return to promise.

Also the instance is not paused until refresh is complete, even after refresh is called more requests are made and they also return 401 or 403 and there is another refresh call.

axios@0.21.1
axios-auth-refresh@3.1.0

**Comment by ghasemikasra39** [comment]
What is the definition of `API.get`?

**Comment by ammarrush** [comment]
> What is the definition of `API.get`?

Its the instance I am exporting from api.js (the first code in my question)

I import it like this import `API from '../../api'`

**Comment by www-chique** [comment]
I'm also having the same problem.
The refresh function and everything works fine, and all in sequence. But the original code which made the call doesn't receive the new resolved promise / data. It's returning some undefined.

**Comment by amcsi** [comment]
I'm also getting the same issue. Though I happened to come across a fairly simple workaround:

before:
```js
createAuthRefreshInterceptor(
  api,
  error => {
    // Maybe the token just expired and we need to refresh it. Let's try that.
    return api
      .post('/refreshEndpoint', {refresh_token: refreshToken})
      .then(response => {
        // some success logic...
        return Promise.resolve();
      })
      .catch(() => {
        // some failure logic...
        return Promise.reject(error);
      });
  },
  // The following option doesn't seem to work.
  { pauseInstanceWhileRefreshing: true }
```

after (see 
```js
// Addition 1/3.
let refreshingPromise = null;

createAuthRefreshInterceptor(
  api,
  error => {
    // Addition 2/3.
    if (refreshingPromise) {
      return refreshingPromise;
    }

    // Maybe the token just expired and we need to refresh it. Let's try that.
    return api
      .post('/refreshEndpoint', {refresh_token: refreshToken})
      .then(response => {
        // some success logic...
        return Promise.resolve();
      })
      .catch(() => {
        // some failure logic...
        return Promise.reject(error);
      })
      // Addition 3/3.
      .finally(() => {
        // Clear the promise so that newer calls to this interceptor would initiate a fresh API call.
        refreshingPromise = null;
      });
  },
  // The following option doesn't seem to work.
  { pauseInstanceWhileRefreshing: true }
```

**Comment by Flyrell** [comment]
Try not to use `pauseInstanceWhileRefreshing` option as this is needed only when your refreshing logic is not an API call. It's basically needed only when you're not able to use `skipAuthRefresh` inside your refreshing logic.

First of all, you need to use the `skipAuthRefresh` for the refreshing call, so when it fails the call itself is not caught by the interceptor (this would create an infinite loop otherwise). Usage: 

```javascript
const refreshAuthLogic = (failedRequest) =>
  axios
    .post(`${process.env.API_BASE_URL}user/refresh/`, getFormData(), { skipAuthRefresh: true })
    // ...
```

This should probably be it. The solution @amcsi suggested is already in the library when you're not using the `pauseInstanceWhileRefreshing` flag. Please, let me know if that worked, thanks.

**Comment by Flyrell** [comment]
Closing for now, will reopen if that doesn't work.

**Comment by ammarrush** [comment]
I tried what you said @Flyrell, it returns to the original promise now but the refresh logic is being run twice for three consecutive api calls. Also, I don’t think I need skipAuthRefresh flag because I actually don’t use the instance to call the api in refresh logic. I tried using instance in the refresh logic with skipAuthRefresh and that also didn’t work.

I changed my code a bit so here it is for reference:

`const refreshAuthLogic = (failedRequest) =>
  axios.post(
    env_variables.url+'user/refresh/',
    getFormData()
  ).then((result)=>{
    logAmplitude('Token Refresh successful')
    localStorage.setItem("token", result.data.access_token);
    localStorage.setItem("refreshToken", result.data.refresh_token);
    failedRequest.response.config.headers['Authorization'] = 'Bearer ' + result.data.access_token;
    return Promise.resolve();
  })
  .catch((error)=>{
    logAmplitude('Token Refresh failed')
            
    const refreshTokVal = localStorage.getItem('refreshToken')
    ? localStorage.getItem('refreshToken')
    : 'No refresh token'
    
    logAmplitude(refreshTokVal)
    Auth.signout();
    window.location.reload(false);
  })`

Create auth func: 

`createAuthRefreshInterceptor(instance, refreshAuthLogic, {
  statusCodes: [401, 403]
});`

Example request scenario: 

`API.get("user/profile/")
      .then((result)=>{
          console.log("ONE SUCCESS")
          console.log(result)
          this.setState({userName: result.data.fullName})
      })

      API.get("user/profile/")
      .then((result)=>{
          console.log("TWO SUCCESS")
          console.log(result)
      })

      API.get("user/profile/")
      .then((result)=>{
          console.log("THREE SUCCESS")
          console.log(result)
      })`
      
      What my network looks like :
      
![image](https://user-images.githubusercontent.com/2511651/143903277-7ccdae8c-6e73-48b1-8c5d-e5295062fa7c.png)
