### ISSUE TITLE
Some questions regarding your library

### ISSUE THREAD

**Issue by ghasemikasra39** [Flyrell/axios-auth-refresh#150]
1. Instead of using `axios` directly, can I create two separate instances of axios, use one for `createAuthRefreshInterceptor ` and use the second for the refreshing call inside the `refreshAuthLogic` function, I want to avoid using `skipAuthRefresh` flag for the  refreshing call:
```javascript
    this.client = axios.create();
    this.clientRefresher = axios.create();

    createAuthRefreshInterceptor(this.client, this.refreshAuthLogic);

  refreshAuthLogic = async (failedRequest) => {
    const tokenResponse = await this.clientRefresher.request(requestConfig);
    const {token, refresh_token} = tokenResponse.data;

    failedRequest.response.config.headers[AUTH_TOKEN_HEADER] = token;
    return Promise.resolve();
  }

```

2. can `refreshAuthLogic` function be an **async** function? (using **async** and **await** inside `refreshAuthLogic` like above)
3. Does this library work fine in React Native?

**Comment by Flyrell** [comment]
Hi @ghasemikasra39, thanks for reaching out and sorry for replying that late 😅 

1. Yes, you can.
2. Yes, you can.
3. No idea, to be honest. Haven't used it with React Native myself, but others seem to use it on a daily basis.
