### ISSUE TITLE
Not exported types

### ISSUE THREAD

**Issue by www-chique** [Flyrell/axios-auth-refresh#170]
Hey, first of all, many thanks for this wonderful project!

The "AxiosAuthRefreshRequestConfig" returns 'any'.
I suspect that is because model.ts is not being exported in the "dist"?
I am a newbie, please excuse if I am not making sense.

![image](https://user-images.githubusercontent.com/29447216/134393256-b576d1cd-05f9-4ce7-a2b7-57a353a75b4e.png)

**Comment by LWilsonDev** [comment]
I'm also having trouble with this, but again, I am fairly new to TS so it's possible I have just set something up incorrectly... 
I am getting this error: ` node_modules/axios-auth-refresh/dist/index.d.ts(2,41): error TS2307: Cannot find module './model' or its corresponding type declaration`
Apologies if this is not related

**Comment by Flyrell** [comment]
Hi, thanks for reporting the issue. Working on a fix right now.

**Comment by Flyrell** [comment]
Fixed in #171
