### ISSUE TITLE
Build target change, accidental ES6 requirement raised?

### ISSUE THREAD

**Issue by StephenBeirlaen** [Flyrell/axios-auth-refresh#172]
Hello!

MR #170 introduced a compiler target change from es5 to es2015 which now results in ES6 syntax appearing in the dist js file (const, =>, ...).
We have some devices that do not support ES6.
Since this change was introduced in a patch release version, it was automatically installed by npm. Was this intended?

**Comment by ScreamZ** [comment]
You should rely on a transpiler like babel to avoid those issues.
