### ISSUE TITLE
Redirect to login on failure

### ISSUE THREAD

**Issue by singhtrustcom** [Flyrell/axios-auth-refresh#174]
How do I redirect to the login page whenever I my refresh token API call got expired or it will throw an error

even i tried with interceptor request  and catch block under "refreshAuthLogic" but this seems to useless for me can you please help me. Is there is any way to do this ?

**Comment by Flyrell** [comment]
Hi @singhtrustcom  Please, if the question still stands, move it to the Q&A section of GitHub Discussions.
