### ISSUE TITLE
Calling mutation instead of Axios request in Interceptor

### ISSUE THREAD

**Issue by degeta10** [Flyrell/axios-auth-refresh#177]
As per your example in docs an Axios request is sent to refresh the token.
But I'm trying to call a mutation instead. 
On doing that I see that for some reason the mutation doesn't work as expected.

Below is the code for refreshLogic:
`const refreshTokenLogic = (failedRequest) => store.dispatch("auth/refreshAuthToken", store.getters["auth/refreshToken"]).then((response) => {
      console.log("updating token");
      failedRequest.response.config.headers["Authorization"] =
        "Bearer" + store.getters["auth/accessToken"];
      return Promise.resolve();
    });
createAuthRefreshInterceptor(axios, refreshTokenLogic);`

Below is the code for mutation:
`refreshAuthToken(state, payload) {
    this.state.app.isLoading = true;
    axios.post("auth/token/refresh", { token: payload }).then((response) => {
        this.state.app.isLoading = false;
        const { data } = response.data;
        localStorage.setItem("auth", JSON.stringify(data));
        state.accessToken = data.access_token;
        state.refreshToken = data.refresh_token;
        state.expiresAt = data.expires_at;
        console.log("completed mutation");
      })
      .catch((error) => {
        this.state.app.isLoading = false;
        this.dispatch("auth/logout");
        Vue.noty.error("Session expired!");
        router.push("login");
      });
  },`

As you can see I've added 2 console logs. But why does the console log from refreshTokenLogic apears before the mutation's log.
Am I doing something wrong here?
[Here](https://ibb.co/VQMkQ8C) is a screenshot of the browser console.

**Comment by Flyrell** [comment]
Please provide minimal code reproduction somewhere accessible, so we can take a look at it. (Might be worth resolving the formatting issues too). Thanks, I'll close it for now.
