### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by revmischa** [Flyrell/axios-auth-refresh#18]
Could not find a declaration file for module 'axios-auth-refresh'. 'node_modules/axios-auth-refresh/dist/index.min.js' implicitly has an 'any' type.
  Try `npm install @types/axios-auth-refresh` if it exists or add a new declaration (.d.ts) file containing `declare module 'axios-auth-refresh';`ts(7016)

**Comment by scambier** [comment]
Do you _need_ TS definitions for this module? It's quite small, you could write them yourself

**Comment by revmischa** [comment]
Yes actually they are needed or it won’t compile without adding that module declaration. 
It’s okay I wrote a sweeter module yesterday anyway https://www.npmjs.com/package/axios-jwt

**Comment by scambier** [comment]
Well, I use it in a VueJS project (in TypeScript) and declarations are not needed. They're never _needed_, If declarations don't exist for a module, you can just `const module = require('module')` like in good old JavaScript.

**Comment by Flyrell** [comment]
@revmischa @scambier In case you're still interested a types, they are available for a few weeks now. No need to drop the typescript's features.

**Comment by rcidaleassumpo** [comment]
> @revmischa @scambier In case you're still interested a types, they are available for a few weeks now. No need to drop the typescript's features.

Hi, from which package ? Because when I try to install from @types/axios-auth-refresh it doesn't find anything.

**Comment by Flyrell** [comment]
@rcidaleassumpo just intall the `axios-auth-refresh`, typing are included.

**Comment by rcidaleassumpo** [comment]
I"m using `"axios-auth-refresh": "^1.0.7`
![Screen Shot 2020-07-20 at 1 48 29 PM](https://user-images.githubusercontent.com/8950622/87934628-b5f3a880-ca8f-11ea-8e7d-b84d19013cf2.png)

I don't get the index.d.ts . Am I missing something ?

**Comment by Flyrell** [comment]
Typings were included in `v2.0.0`. I highly recommend you to update the package to the current version `v2.2.8`.

**Comment by rcidaleassumpo** [comment]
Totally awesome my friend, I just did the `npm i axios-auth-refresh`. I wasn't aware that there was a 2v version already. Thank you ;)
