### ISSUE TITLE
How to handle a 401 "Refresh token is invalid" error

### ISSUE THREAD

**Issue by denisoed** [Flyrell/axios-auth-refresh#191]
If the refresh_token is not valid, you need to redirect to the authorization page, but for some reason I can't catch the error.

```js
async function handleRefreshError(failedRequest: any) {
  try {
    const resp = await refreshToken()
    failedRequest.response.config.headers.Authorization = `Bearer ${resp.access_token}`
  } catch (error) {
    console.log('Redirect to login page') // >>> NOT WORKING
  }
}

...

createAuthRefreshInterceptor(api, handleRefreshError)
```

How to intercept refresh token error?

**Comment by denisoed** [comment]
My solution:

1. Create two instances

```js
const axiosParams = {
  baseURL: process.env.VUE_APP_BASE_API_URL,
  withCredentials: true,
  headers: { 'Content-Type': 'application/json' },
}
const baseApi = axios.create(axiosParams)
const refreshApi = axios.create(axiosParams)
```
2. Create `refresh` & `logout` handlers

```js
async function handleRefreshError(failedRequest: any) {
  try {
    const resp = await refreshApi.post(AUTH_TOKEN_REFRESH_URL, { refresh_token })
    failedRequest.response.config.headers.Authorization = `${TOKEN_TYPE} ${resp.data.access_token}`
    return Promise.resolve()
  } catch (error) {
    return Promise.reject(error)
  }
}

async function handleRefreshFailed() {
  try {
    window.location.href = LOGIN_ROUTE
    return Promise.resolve()
  } catch (error) {
    return Promise.reject(error)
  }
}
```

3. Init `createAuthRefreshInterceptor` funcs

```js
createAuthRefreshInterceptor(baseApi, handleRefreshError)
createAuthRefreshInterceptor(refreshApi, handleRefreshFailed, {
  statusCodes: [401, 422, 403],
})
```

4. Finish!

**baseApi** - This instance should be used for all requests in the application.
**refreshApi** - This instance should only be used for token refresh requests.

**Comment by Flyrell** [comment]
Thank you @denisoed for responding. Your suggestion is completely right. Will close this for now.

**Comment by huyvu23** [comment]
> To solve this problem you need to create two instances
> 
> **baseApi** - This instance should be used for all requests in the application. **refreshApi** - This instance should only be used for token refresh requests.
> 
> My solution:
> 
> 1. Create two instances
> 
> const axiosParams = {
>   baseURL: process.env.VUE_APP_BASE_API_URL,
>   withCredentials: true,
>   headers: { 'Content-Type': 'application/json' },
> }
> const baseApi = axios.create(axiosParams)
> const refreshApi = axios.create(axiosParams)
> 2. Create `refresh` & `logout` handlers
> 
> async function handleAuthError(failedRequest: any) {
>   try {
>     const resp = await refreshApi.post(AUTH_TOKEN_REFRESH_URL, { refresh_token })
>     failedRequest.response.config.headers.Authorization = `${TOKEN_TYPE} ${resp.data.access_token}`
>     return Promise.resolve()
>   } catch (error) {
>     return Promise.reject(error)
>   }
> }
> 
> async function handleRefreshFailed() {
>   try {
>     window.location.href = LOGIN_ROUTE
>     return Promise.resolve()
>   } catch (error) {
>     return Promise.reject(error)
>   }
> }
> 3. Init `createAuthRefreshInterceptor` funcs
> 
> createAuthRefreshInterceptor(baseApi, handleRefreshError)
> createAuthRefreshInterceptor(refreshApi, handleRefreshFailed, {
>   statusCodes: [401, 422, 403],
> })
> 4. Finish!

where function handleRefreshError ?

**Comment by huyvu23** [comment]
> Thank you [@denisoed](https://github.com/denisoed) for responding. Your suggestion is completely right. Will close this for now.

this not work for me , you can fix that ?
