### ISSUE TITLE
Document whether all interceptors are rerun after refresh

### ISSUE THREAD

**Issue by tibbe** [Flyrell/axios-auth-refresh#195]
It's a bit unclear from the docs what interceptors are (re-)run once the fresh is done. For example, if we have two interceptors:

1. Add the Authorization header (e.g. by retrieving a JWT from local storage).
2. `refreshAuthLogic`

What happens to

- The request that triggered the auth refresh? Does both (1) and (2) get rerun for this request or only interceptors after (2), if any?
- Any requests that got paused? Did they get paused before or after (1)?

**Comment by Flyrell** [comment]
This is more of an axios-related question as to how the interceptors are running, but as far as I remember (I haven't work with axios for a while now) the request interceptors are no longer ran for the request caught in `refreshAuthLogic`. Might be work to double-check with the axios thought.
