### ISSUE TITLE
Each call is getting duplicated

### ISSUE THREAD

**Issue by umstek** [Flyrell/axios-auth-refresh#196]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/7861481/176670603-bb93db30-d8ca-4f58-9e1d-2f67dfe061a4.png">
As you can see here, (except the preflight) two requests are made per each request, one with auth token and one without.

**Comment by Flyrell** [comment]
Please provide minimal reproduction somewhere we can see. Thank you, I'll closing this for now.
