### ISSUE TITLE
Bug with axios.create and baseURL option?

### ISSUE THREAD

**Issue by sustained** [Flyrell/axios-auth-refresh#20]
First let me just say thanks for creating a great little library.

I think I've found a bug.

I set my JWT TTL to 60 seconds but the refresh TTL longer so that I can debug this JWT stuff and get it working.

So, I log into my application and then wait > 60 seconds, then I hit an authenticated route `/api/auth/me` and get a 401.

The interceptor kicks in and hits the refresh token route (`/api/auth/refresh`), which returns a new token and all that jazz.

After that, I see the original route that triggered the 401 getting hit again... except for one slight problem - It's hitting `/api/api/auth/me`. The `api` part is now doubled.

**Comment by Flyrell** [comment]
Hi. Thanks for the issue. 

Can you please share your code for the interceptor and other things associated with it (like the actual call, other interceptors, etc.) ?

**Comment by sustained** [comment]
I followed the docs exactly and don't have any other interceptors.

I removed the `baseURL` of `api` from `axios.create` and prefixed all my axios calls with `/api` and the error went away so I'm almost certain it's your library.

**Comment by Flyrell** [comment]
Inside your `refreshAuthLogic` callback, just unset the baseURL. Unfortunately, this is a problem with axios (not sure if that's the problem or desired behavior). I can't find the source I know it from, but here's the actual implementation I did when I was explaining the library a bit. [StackOverflow answer](https://stackoverflow.com/questions/51563821/axios-interceptors-retry-original-request-and-access-original-promise/51600050#51600050). 

The thing is, url in axios' error config is the full url and the config still has the `baseURL` option set.

I didn't want to change this, as this should be "just an interceptor" and I don't want people to get confused. Please, let me know if that helped. 

Thanks

But the thing here is

**Comment by sustained** [comment]
Hrm... that feels terrible hacky but it is *a* solution so I'll bear it in mind, thanks.

Think it's worth an issue on the axios tracker? I'm not really sure I know enough about either library to be the one to file it though.

Thanks for the responses!

**Comment by Flyrell** [comment]
As I said earlier, I'm not sure if that's a bug or desired behavior. Either way, it feels like it shouldn't be like that, so it might be worth opening the issue and see what axios team has to say about it. 

If you do so, please, refer to this issue, so anyone with the same problem can see the thread.

Thanks.

**Comment by jackmu95** [comment]
Resetting the `baseURL` works for the initial failing request but queued requests have the same issue and there is currently no solution to adjust those.

IMHO there should be a global `baseURL` handling or a config option to define a callback for queued requests to be able transform their configs too.
