### ISSUE TITLE
Catching 401 Unauthorized or Bad Request if the refresh token fails

### ISSUE THREAD

**Issue by deanilvincent** [Flyrell/axios-auth-refresh#26]
Good day,

I just recently installed this package on my project. I created a validation in my refresh token web api if the refresh token is valid or not. If it's not valid, it will return an "Unauthorized" 401 response to the client side. 

I tried this code from the readme note and I added `catch` exception but the `catch` exception doesn't work.

```
 const tokens = {
     token: localStorage.getItem("token"),
     refreshToken: localStorage.getItem("refreshToken")
};

// Function that will be called to refresh authorization
const refreshAuthLogic = failedRequest => axios.post(`api/token/refresh`, tokens).then(response => {
    localStorage.setItem("token", response.data.token);
    localStorage.setItem("refreshToken", response.data.refreshToken);
    failedRequest.response.config.headers['Authentication'] = 'Bearer ' + response.data.token;
    return Promise.resolve();
}).catch(error=>{ // I added this but it doesn't work
    alert('Token is invalid. Please re-login your account')
})

// Instantiate the interceptor (you can chain it as it returns the axios instance)
createAuthRefreshInterceptor(axios, refreshAuthLogic);

axios.interceptors.request.use(request => {
    request.headers['Authorization'] = `Bearer ${this.getToken()}`;
    return request;
});
```
Package version: `"axios-auth-refresh": "^1.0.7"`

Dziekuje in advance!

**Comment by Flyrell** [comment]
Please provide the minimal reproduction so we can see whats wrong.

**Comment by Flyrell** [comment]
I'm closing the issue since there was no response. We can re-open it if you haven't resolve the issue yet, just please provide the minimal reproduction, so we can simulate this.
