### ISSUE TITLE
Include in documentation that this project can do more than its name

### ISSUE THREAD

**Issue by amcsi** [Flyrell/axios-auth-refresh#31]
This project is great, and I was able to not only handle automatic token refreshing on 401 status codes, but also automatic request throttling on 429 Too Many Requests status codes as well (reading the Retry-After header to detemine how many seconds to to call a `setTimeout()`).

The issue is that I had doubts at first to try and implement this in my project, because this library's name is `axios-auth-refresh`, and the readme also doesn't mention being able to use this library for other types of retry requests.

It would be cool to include in the readme some encouragement to use this library for other cases other than refreshing tokens.

**Comment by LeoniePhiline** [comment]
I'm also using it to display OTP challenges (with Google2FA and Laravel on the API side).
It's really a nice wrapper to the axios interceptor mechanics.

**Comment by Flyrell** [comment]
Hi, thanks for the kinds words. Unfortunately, I can't think of any edit I can make to documentation that would suggest it can do the things you've mentioned here. Surely, it'd be great, to include it, but I'm not sure how to call it or suggest it... would the list do the thing? Like...

*This library has also been used for:*
- Automatic request throttling by @amcsi 
- OTP challenges with Google2FA by @LeoniePhiline 

Would it be ok with you? I'd then add it to the docs and maybe it will encourage people to try using the package for the things it has not been originally built for with the possibility to add their experiments to the docs.

**Comment by LeoniePhiline** [comment]
Oh that's sure okay by me!

**Comment by amcsi** [comment]
Yeah, I'm good with this too!

**Comment by Flyrell** [comment]
Merged in #64.
