### ISSUE TITLE
[2.x] Skip interceptor on specific endpoints

### ISSUE THREAD

**Issue by antonkomarev** [Flyrell/axios-auth-refresh#41]
I faced the situation that on failed login action server respond with `401` error additional information `error: "invalid_credentials"` but interceptor started to refresh token because it treats all `401` errors as expired token. It will be good to have mechanism to exclude interception of the specific endpoints.

I've thought about this syntax:
```js
createAuthRefreshInterceptor(axios, refreshAccessToken, {
    excludeEndpoints: {
       '/login' : {'post'},
    }
});
```

This implementation will have issues with ignoring endpoints like `PATCH /products/104` because it will require to add wildcards support and it will bring too much complexity to the package.

**Comment by Flyrell** [comment]
There's an option to skip interceptor for specific calls, isn't it an option for you? It's in beta now, but after your great work with contributions I guess you're already working on a beta.

**Comment by antonkomarev** [comment]
Ah, sorry, I've missed this new feature. It should be enough:

```js
export const postLogout = () => (
    httpClient.post('/logout', {}, {
        skipAuthRefresh: true,
    })
);
```

**Comment by antonkomarev** [comment]
Reopened issue because I realize that `error.config.skipAuthRefresh` is `undefined` in interceptor. Trying to debug and understand why is this happening.

**Comment by Flyrell** [comment]
@antonkomarev aren't you using axios@0.19? They messed up custom properties in 0.19 and we're waiting for the fix. See [axios#2295](https://github.com/axios/axios/issues/2295)

**Comment by antonkomarev** [comment]
Yes. Axios 0.19 :(

**Comment by antonkomarev** [comment]
I've installed 0.18.1 and it's working well.

**Comment by hardfi** [comment]
Is there any TS support for this? Or just:
```
  config?: AxiosRequestConfig & { skipAuthRefresh?: boolean };
```

Thanks for the good lib anyway 👏
