### ISSUE TITLE
How should I automatically replay the first failed call?

### ISSUE THREAD

**Issue by mjsarfatti** [Flyrell/axios-auth-refresh#5]
There is something I'm missing...
I've implemented the library (and also read through https://stackoverflow.com/questions/51563821/axios-interceptors-retry-original-request-and-access-original-promise - but since I'm on React it doesn't fully apply).
If a call gets rejected with 401, the refresh call is sent automatically, and it does refresh the token.
But shouldn't it also replay the original call once it receives the token?
Is that part left to us to implement? And what would a good strategy be, in broad terms?

**Comment by Flyrell** [comment]
Of course it should, that's why you need to return the Promise from `refreshTokenFunction`. 

For example:
```javascript
import axios from 'axios';
import refreshAuth from 'axios-auth-refresh';

refreshAuth(axios, function refreshTokenFunction () {
    return axios.get('/some/url/to/obtain/new/token').then(() => /* do whatever is needed */);
});

axios.get('/route/with/auth/guard')  
    // auth error occurs
    // refreshTokenFunction is called
    // axios.get('/some/url/...') is called
    // then (or error)  of axios.get('/some/url/...') is called
    // then is returned from refreshTokenFunction (Promise)
    .then(_ => console.log('wow, it works'));
```

If this is not working, please try to reproduce the problem and let me see the code to further investigate what is wrong.

**Comment by mjsarfatti** [comment]
Nevermind, it works as expected :). It was a problem with an undefined `this` in my _refreshAuth_ function, which triggered an exception, but only after the refresh call succeeded.

All good 👍
