### ISSUE TITLE
Why all the functions are exported?

### ISSUE THREAD

**Issue by antonkomarev** [Flyrell/axios-auth-refresh#53]
What is the reason to export all these functions?

- `mergeOptions`
- `shouldInterceptError`
- `createRefreshCall`
- `createRequestQueueInterceptor`
- `unsetCache`

From my point of view they are all internal and should stay private.

**Comment by Flyrell** [comment]
They've been exported only for the tests. I can think of two solutions for them to be testable and still "logically" correct:
- move them to a separate file like the `utilities.ts` and import them in the index and in the tests
- use a package like [`rewire`](https://www.npmjs.com/package/rewire) for the tests and remove the exports

**Comment by antonkomarev** [comment]
Thank you for the explanation. I was thinking about the tests, but was unsure.
