### ISSUE TITLE
Axios error.response is null 

### ISSUE THREAD

**Issue by israelKusayev** [Flyrell/axios-auth-refresh#57]
I have a POST request that sends multipart/form-data.  

When the server returns 401 to this call, Axios throw a "network error"  

it's a [known](https://github.com/axios/axios/issues/383#issuecomment-282388675) problem in Axios

so your interceptor check
```javascript
 if (!error.response || !options.statusCodes.includes(parseInt(error.response.status))) {
        return false;
    }
```

And because the error.response is null the interceptor doesn't work

What should I do?

**Comment by Flyrell** [comment]
Sorry but I can't find anything that says that the `multipart/form-data` request triggers the uncatchable `Network error` as you said. Is there any chance you misunderstood it? If not, then I guess there would be a problem to catch it and fo anything with it, as the interceptor will be unable to parse the error's status code.

Anyway, it's possible to [skip the individual request](https://github.com/Flyrell/axios-auth-refresh#skipping-the-interceptor-beta) and write your own logic for refreshing them. Maybe that would be the case.

**Comment by israelKusayev** [comment]
I'm not sure if it's because of the `multipart/form-data`

but as you can see [HERE](https://github.com/axios/axios/issues/383#issuecomment-282388675) a lot of people getting network error when the server returns 401  

so, in this case, the interceptor won't work

**Comment by Flyrell** [comment]
Yes I saw it, but I also read almost the whole thread and most of them have had an issues with CORS or incorrect server configuration 😐
