### ISSUE TITLE
Intercepted requests should be updated with new access_token

### ISSUE THREAD

**Issue by MarkVesterskov** [Flyrell/axios-auth-refresh#7]
First of all, i absolutely love this plugin - made my life real easy refreshing tokens in a new project im working on.

For the sake of it, i tried added sleep(10) to my backend API refresh function, to see how the plugin would handle additional intercepted requests. They're intercepted correctly, and run when the refresh request finishes BUT - they're not updated with the newly fetched access_token, so they spawn up a new refresh request per request, thus slowing down all subsequent requests, and making N new (unnecessary) access tokens.

Would it be possible to update the Authentication headers on all waiting requests with the newly fetched token? I'd love to do a PR but my Promises skills are extremely limited.

**Comment by Flyrell** [comment]
Hi Mark,

thank you for the kind words. I'm really happy to see this library to actually help someone.

I see what you mean and I completely agree with you; There should be some control of the requests waiting for the auth refresh, so we can configure them properly. I'm usually binding `Authorization ` header to the requests with an interceptor, that means if I update my token before request is actually called, I always get the fresh token.

```javascript
axios.interceptors.request.use(request => {
    request.headers['Authorization'] = getTokenLogic();
    return request;
});
```

Of course, I know that using interceptors for everything is not necessary a good think and there are some cases when this would not work properly, so I will take a look at it and I might come up with something.

**Comment by MarkVesterskov** [comment]
Thanks for the swift reply! I am too using interceptors, but not wrapping the token logic in a function, thus i get the old token attached to the request - I'll update my code using your above example, thanks!
