### ISSUE TITLE
401 not trigger interceptor sometimes

### ISSUE THREAD

**Issue by imchivaa** [Flyrell/axios-auth-refresh#9]
Hi there, first of all, thanks for the plugin. 

My problem with the plugin is that sometimes, it doesn't hit the refreshToken method specified in `createAuthRefreshInterceptor`. Below is my sample implementation, it worked on some page, for example, if i have multiple API call in that page that return 401, then request interceptor get called and the refresh token method as well. But if i have a single api call on that page, then it simple doesn't work as intended in my case. 

```

/*retrieve latest accessToken from localstorage*/
function getAccessToken(){
    return localStorage.getItem('accessToken');
}

/*perform refresh token action by calling vuex store refreshSession method*/
const refreshToken = failedRequest => store.dispatch('refreshSession')
.then(response => {
    failedRequest.response.config.headers = getHeaders();
    return Promise.resolve(failedRequest);
})
.catch((error) => {
	store.dispatch('logout');
	router.push({ name: 'Login' });
    return Promise.reject(error);
});

/*axios request interceptor */
axios.interceptors.request.use(request => {
    createAuthRefreshInterceptor(axios, refreshToken);
    request.headers['Authorization'] = 'Bearer ' + getAccessToken();
    return request;
});
```

Hope you can point out my mistakes in the above implementation, thank you.

**Comment by imchivaa** [comment]
update: I think the axios interceptor only not getting triggered during hard refresh or during
```
next({
        name: 'Dashboard',
})
```
in router.js, the issue i am facing is if isAuth flag set to true, and if they visited login page, router will check and route them to dashboard, that's when i hit the above issue.

**Comment by imchivaa** [comment]
It's okay, problem solved. i use the same instance of axios.

**Comment by imchivaa** [comment]
Sorry, after some testing, i am to reproduce the issue. Any advice? Thanks.

**Comment by Flyrell** [comment]
This is probably because you initialize the interceptor inside the interceptor. This is the correct way of doing it:

```javascript
createAuthRefreshInterceptor(axios, refreshToken);
axios.interceptors.request.use(request => {
    request.headers['Authorization'] = 'Bearer ' + getAccessToken();
    return request;
});
```

**Comment by imchivaa** [comment]
Ah, yea it works. Thanks @Flyrell ... :)
