### ISSUE TITLE
err without err.response

### ISSUE THREAD

**Issue by igordeoliveirasa** [Flyrell/axios-auth-refresh#94]
I wish I could return Promise.reject(err) when err is already the response... Its because my app has the following interceptor:

`axios.interceptors.response.use((response) => {
    return response;
}, function (error) {
    return Promise.reject(error.response);
});`

Thanks in advance...

**Comment by Flyrell** [comment]
Sorry for the late response @igordeoliveirasa. I'm not sure what you mean exactly. Would you be able to share a bit of code so I can get the idea? Thanks

**Comment by v1talii-dev** [comment]
I have the same problem. When the token is expired, the frontend executes a request, which returns with a 401 response code. After that, the interceptor from axios-auth-refresh is called and the request is made to refresh the token. The token is successfully refreshed and an attempt is made to resubmit the original request. But the initial request is erroneous, and the interceptor does not receive an object of the form `{ response: { data: { msg: 'error msg' } }, status: 5xx, ... }`, but a simple object located along the path `response.data` = `{ msg: 'error msg' }`.

My interceptor:
```js
axios.interceptors.response.use(
  response => response,

  error => {
    console.log(error.response); // undefined
    console.log(error.response?.data); // undefined
    return Promise.reject(error);
  }
);
```
