### ISSUE TITLE
createAuthRefreshInterceptor intercepts the request after the axios request interceptor

### ISSUE THREAD

**Issue by melikpehlivanov** [Flyrell/axios-auth-refresh#95]
Hello, I've the following code - https://pastebin.com/qYvfivqv

The problem is that when I get 401 unauthorized response the authRefreshInterceptor executes successfully but in the meantime the api.interceptors.request is executed with the old token and I have to refresh the page in order to get the new one. Any ideas ? Thanks in advance!

**Comment by ErickMaeda** [comment]
Hello @melikpehlivanov , I'm having the same issue.

Can you please share your solution? Thanks!

**Comment by melikpehlivanov** [comment]
Sure, @ErickMaeda 

This is my axios helper
`import Axios from "axios";
import { toast } from "react-toastify";
import { history } from "../..";
import { setUserInLocalStorage } from "./localStorage";

const api = Axios.create({
  baseURL: your url,
  withCredentials: true,
});
let authTokenRequest;

// This function makes a call to get the auth token
// or it returns the same promise as an in-progress call to get the auth token
function getAuthToken() {
  if (!authTokenRequest) {
    authTokenRequest = api
      .post(your refresh token url goes here, {})
      .then((tokenRefreshResponse) => tokenRefreshResponse);
    authTokenRequest.then(resetAuthTokenRequest, resetAuthTokenRequest);
  }

  return authTokenRequest;
}

function resetAuthTokenRequest() {
  authTokenRequest = null;
}

export const setupAxiosInterceptor = (signOut) => {
  api.interceptors.response.use(
    (response) => response,
    (error) => {
      if (error.response.status === 401 && !error.config._retry) {
        return getAuthToken().then((response) => {
          setUserInLocalStorage(response);
          error.response.config.__isRetryRequest = true;
          return api(error.response.config);
        });
      }
    }
  );
};

export default api;
`

**Comment by Bartyee** [comment]
> Sure, @ErickMaeda
> 
> This is my axios [helper](https://pastebin.com/1zxVxr4M)

Hi. Did you fix that?
