### ISSUE TITLE
Intercepted Request Doesn't Refire, Goes into Infinite Loop

### ISSUE THREAD

**Issue by altimas** [Flyrell/axios-auth-refresh#97]
My refresh Auth Logic is built like this. 

``` const refreshAuthLogic = (failedRequest) => {
    const refreshTokenRequest = new AuthApi({ basePath: SURELY_API_BASE_URL });
    const storedRefreshToken = localStorage.getItem(REFRESH_TOKEN_ACCESSOR);
    if (storedRefreshToken && storedRefreshToken !== '') {
        return refreshTokenRequest
            .refreshToken({ refreshToken: storedRefreshToken })
            .then((tokenRefreshResponse) => {
                setTokens(tokenRefreshResponse.data);
                failedRequest.response.config.headers[
                    'Authorization'
                ] = `Bearer ${tokenRefreshResponse.data.accessToken}`;
                return Promise.resolve();
            })
            .catch((error) => {
                clearTokens();
                return Promise.reject(error);
            });
    } else {
        return Promise.reject();
    }
};

export default refreshAuthLogic;
```

And I am initiating it like this in my App.tsx

```
createAuthRefreshInterceptor(axios, refreshAuthLogic);
```

And everytime a 401 goes through it just locks up my app infinitely and never refires the request, but using debugging and console logs it does get right up to the return statement within the if statement. Any ideas on what I am missing?

**Comment by altimas** [comment]
Okay finally figured it out.

Was using openapi-generator to basically generate all our API methods with as axios requests, but something about the way it was generating those didn't return the same thing as the normal axios instance was. So I converted the above to just using axios.post('URL', params) and it worked like a charm.

**Comment by Flyrell** [comment]
Good to know @altimas and I'm happy you figured that out. Will take a look at the openapi-generator before the next major release if there's anything I can do about it. In the meantime, in case anyone doesn't want to wait I will be happy to collaborate on any related PRs. Hope you don't mind me closing this issue for now.
